### ISSUE TITLE
DSN Converter not properly converting bottom pads

### ISSUE THREAD

**Issue by seveibar** [tscircuit/dsn-converter#70]
![Image](https://github.com/user-attachments/assets/2cd15298-898b-44b9-876a-ce85c28dd937)

**Comment by seveibar** [comment]
CC @imrishabh18

**Comment by seveibar** [comment]
ooh actually it might be the trace conversion

**Comment by seveibar** [comment]
Do we properly convert this `ses` and `dsn` properly back from freerouting with traces on the same layer?

[input (4).dsn.txt](https://github.com/user-attachments/files/18205922/input.4.dsn.txt)
[output (1).ses.txt](https://github.com/user-attachments/files/18205926/output.1.ses.txt)

**Comment by imrishabh18** [comment]
I think it might be because we are not converting the pad layer from circuit json to dsn

**Comment by imrishabh18** [comment]
It's fixed now, the dsn version which was calculating the layer was not updated in the registry-api.
